import type { Metadata } from "next";
import { PT_Serif, Space_Grotesk, Space_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const sans = Space_Grotesk({
  variable: "--font-theme-sans",
  subsets: ["latin"],
});

const serif = PT_Serif({
  variable: "--font-theme-serif",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const mono = Space_Mono({
  variable: "--font-theme-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "NIDC Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sans.variable} ${serif.variable} ${mono.variable} dark h-full antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
